### PR TITLE
[Contest] add update contest status api

### PR DESCRIPTION
**Pull request by rootial**
## Summary

- Add User Permissions boolean to the DB on the Users table for admin access rights check
- Create new POST API request to enter status update information into the database for contests
  - Perform permissions checks on the API request to make sure only ADMIN users can POST to it
  - Validate that status is one of the following:
    -  0 - Fund Raising 1 - Drafting in Progress 2 - Submission in Progress 3 - Receiving Bill Number 
      4 - 1st Committee 5 - 1st Chamber 6 - 2nd Committee 7 - 2nd Chamber 8 - Executive 
-  Update GET /contest/{id} call to return the new status flag
- Update JWT token to include admin flag

## Test

test in docker

### register new user

```
curl --location --request POST 'localhost:8080/register' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw '{
    "email": "abcd@abc.com",
    "password": "testPass"
}'
```

```
{
    "jwttoken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNkQGFiYy5jb20iLCJhZG1pbiI6ZmFsc2UsImV4cCI6MTYyMTM0Njk5MX0.6XOebgqqGXFUGKGxjy6sg-iLxIiIsIEK2nQB-3sgOJN3dFhzfVVvuFzHxl7MW9qLySoJU_ZEPdP9_NL2bLT7fw",
    "user": {
        "first_name": null,
        "last_name": null,
        "email": "abcd@abc.com",
        "admin": false
    }
}
```

### update status with non-admin
```
curl --location --request POST 'localhost:8080/contest/1/updateStatus' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNkQGFiYy5jb20iLCJhZG1pbiI6ZmFsc2UsImV4cCI6MTYyMTM0Njk5MX0.6XOebgqqGXFUGKGxjy6sg-iLxIiIsIEK2nQB-3sgOJN3dFhzfVVvuFzHxl7MW9qLySoJU_ZEPdP9_NL2bLT7fw' \
--data-raw '{
  "status": 2
}'

```

```
{
    "error": "Unauthorized",
    "detail": "You are not authorized to update this contest"
}
```

### update status with admin

```
curl --location --request POST 'localhost:8080/contest/1/updateStatus' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYmNkQGFiYy5jb20iLCJleHAiOjE2MjEzNDYwNDV9.BniypO15ZrC6e8-DSsXDrHgTAPI6i8vQX8xRXayUEjfa_UjBKWzf1mQ4Z0lRdj_wmVBWkbjkNSJ5enAnEHx2Rg' \
--data-raw '{
  "status": 2
}'

```

```
{
    "id": 1,
    "title": "test contest",
    "endDate": "2021-05-11T19:50:11.000+00:00",
    "prize": 0,
    "rules": "dd",
    "criteria": "",
    "approved": true,
    "description": "",
    "author": {
        "first_name": "Michael",
        "last_name": "Conlon",
        "email": "michael@conlon.io",
        "admin": false
    },
    "status": {
        "id": 2,
        "status": "Submission in Progress"
    }
}

```

### update contest with invalid status
```
{
    "error": "Contest Not Found",
    "detail": "The specified contest status is invalid"
}

```

## Review
@MichaelConlon

### CODE REVIEW

**Comment by rootial** [comment]
@MichaelConlon Hi Michael, i almost finished the implementation of this feature, i got some errors while testing it via docker command in the read me file.
when i try to login through the email and password in the test table file, it throws error saying table not found. 
Seems like the docker build without creating the table. Do u know what i should do to test it?
thanks
```Table "USERS" not found; SQL statement:

select userentity0_.id as id1_4_, userentity0_.admin as admin2_4_, userentity0_.email as email3_4_, userentity0_.first_name as first_na4_4_```

**Comment by MichaelConlon** [comment]
Hi @rootial, Currently our docker build process does not build a database. You will need to run your own local postgres instance. You can create the current DB with the `db/db_tables.sql` script. After setting up the local instance you can set the `postgres_url`, `postgres_pass`, and `postgres_pass` fields in the docker run command to your local db. 

Please also include any DB update scripts that you may have used to update the database.

Sorry for the confusion

**Comment by rootial** [comment]
i try to setup the DB in docker successfully, and when i try to login i got the error. 
Do u know how to solve this?

@MichaelConlon 
```
2021-04-27 16:40:17.757 WARN 1 --- [nio-8080-exec-1] o.s.s.c.bcrypt.BCryptPasswordEncoder : Encoded password does not look like BCrypt


```

**Comment by MichaelConlon** [comment]
@rootial there is another PR in progress that should solve this concern soon

**Comment by MichaelConlon** [comment]
If you pull the latest version of the master branch you should now be able to run `docker-compose up`. This will create the database and run the backend. 
**NOTE:** The file `db_tables.sql` has been renamed to `2_db_tables.sql` as part of the docker compose updates. I believe that change should merge without problem but if not you may have to copy your changes to that file.

**Comment by rootial** [comment]
@MichaelConlon please take a look this pr. i have tested it locally.

**Pull request merged**
